apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: database-password
spec:
  encryptedData:
    PASSWORD: AgCDK93P/ObHkUMVwD4iUdQOccgs2FM7vduyMf6VpHh3BDpW8D1972f1a8F9YPFQ4q5Ip7prc5PgdMQcXF4KLF7G0gvhO/F0ekxVEGeOhmMOqGqqaEvcZUPyU6fuwb4tGlJhivmq9AS7dHotLS3eZyZa31mJhYjdcbdOPwavhCJ05hsB1i9mvTb4s2TYm360Eg0h8tmeUorAg9IMD0Lp8vjAlZb+TFZ3v0bXcfhAU2j3zbLtPIv0eBGh3aogrebsxCTz5qHh98KFL/I96EpcrEFssQTjS+uFJp9tFBhkGsIFLRvmjDY2q8OBBzh4bmAlgO2BsyJ3DZwEEOTxBDGY5JUuEMtjAxIoM6jW3A3InRTJz0nlFzOhS9OZ/+rcT+gxI9BH29UimQhYONNKQ6/rZU9xr4QG7+MsZXKYSUUGDYrSHkHiNFKr1lu/kgM3mxEG3ZjuuWTcEQhefsi1ddlxrRBFA5rD14gEBeA1AgQDsFR+1etoTBqnyK7OIBCK8QGHkoYnE7duISbeq9YGGFC5tl8IISbMHLk4EnSqaOVLpxbeMrhRrKCTxi1VHGvpwMvdaaDhxx/3/qSH+/Hept5lvQdNQfRFeo6OUy3WOyvLR/ij/PeECsSep8tktmTNYyga6v7i6/9PYkriR5mPX+0Wa5tkW6uhTTumXzEYCwkAl3U99esPIEjxQNnykuHB7FNi/nWbk2aSgRD+goX9aw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: database-password

