apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: logging-api-token
spec:
  encryptedData:
    TOKEN: AgBmjUP1rp9WilPVjpn2klVqmAn1m/r4h+KRQEG0c84zCpOZj3n5waU91szTZ+/d+aY3AGVDInUfnDlb3a8dBFCiWmP9xdvqYmdPZjhJHYgjVp73SnUsstfMZ//k8NQ1FXtOXGJ/MvPiRyCZYUbYHdwffX/mOObBjKKD2/bJk94AKtf1I5HFrlmVQcxJxDtEbr4S3BH0ANHfHqp5G75ItpJm+ev4KqHxkPL23LDNUYom9HLLzBCvVRtdFm/R6fnFlW62v/6LNYeW+Fk3BrVxEbHIlFSHQH5te21GpZ3UGqFueyxNKROeeWMKVUOBWalk1zVclHhjVGJgIhasTQJklOz1ivB6oMFyi0yYwK/fGv7NoY9Od5mZOoR+MHXxo33GOP1WAiS0Ib7sRB8+yfGeZMqWmgB/z1Z5sRKjeUT5UKgTcBKMD2t5guUFRLZp73qKfuuZBuWpjEoAB60aUHMFXnKr1nQEK3JQhk4dzy35m4ubl3jspBgHod8P1RWGEHtgZfBEvK3UxpYmDieMMWDmAkikc/N5Emyia7uLN6IWDzA5CSwTl1DTDIqB5yf6sefcWgbHmycerzZhEURieZ0yiQv5H3x5ZpukEArNn5ZPWZttJ1ppvFbFX4cpriT0leaaszJnp83jPqu/Yvil7MujZsJk6cnp5ks8dMu14762V+p+lVdxrAN2PJz4dKrBLZVOrCR4soly+vg=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: logging-api-token

